# Site Settings
title: "Justin Wasner's Project Portfolio"
description: "Project portfolio showcasing data analysis projects"
url: "https://jdwasner.github.io"
baseurl: ""

# Author Information
author:
  name: "Justin Wasner"
  email: "jdwasner@gmail.com"
  github: "jdwasner"
  linkedin: "justin-wasner-871a7791"

# Build Settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "About"
    url: /about

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Kramdown Settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
