# Site Settings
title: "Justin's Project Portfolio"
url: "https://jdwasner.github.io"
baseurl: ""

# Author Information
author:
  name: "Justin Wasner"
  email: "jdwasner@gmail.com"
  github: "jdwasner"
  linkedin: "justin-wasner-871a7791"

# Build Settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Include
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects
  - title: "About"
    url: /about

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Kramdown Settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Coming Soon Projects
coming_soon_projects:
  - title: "Equipment Shifting Calculator"
    description: "Maintenance tool built in Excel to help ensure healthy equipment moves line-side"
    skills:
      - Excel
      - Power Query
  - title: "Ticket to Ride Optimization"
    description: "Analysis of Ticket to Ride board game strategies using Monte Carlo simulations to determine optimal gameplay"
    skills:
      - Python
      - Numpy
      - Matplotlib
  - title: "Sister Plant Misalignment Findings"
    description: "Comparison of sister plant process data to identify misalignments and areas for improvement"
    skills:
      - Power BI
  - title: Runway Direction vs Annual Wind Analysis
    description: "Analysis of airport runway directions compared to annual wind data to assess alignment country wide"
    skills:
      - Python
      - Pandas
      - Matplotlib
      - Geospatial Analysis
